### ISSUE TITLE
Possible redundant code in devito/propagator.py, sympy_to_cgen() method and what does _pre_kernel_steps do?

### ISSUE THREAD

**Issue by Richard-zhang** [opesci/devito#121]
```python
        stmts = []

        for equality in stencils:
            stencil = self.convert_equality_to_cgen(equality)
            stmts.append(stencil)

        kernel = self._pre_kernel_steps
        kernel += stmts
        kernel += self._post_kernel_steps

        return cgen.Block(factors+decl+kernel)
```

When I comment out `kernal = self._pre_kernel_steps`, devito will generate exactly the same file without commenting it. 

Could someone explain what does it do? What exactly is `self._pre_kernel_steps`?
I also found out `_pre_kernel_steps` is exactly the same as the `stmts` and `_pre_kernel_steps` will also vary as `stmts` varies. 

For example, if I add a line of code  `stmts.append(cgen.Assign("testing", "justForTesting()"))` before `kernel = self._pre_kernel_steps`. The `_pre_kernel_steps` will also contain one more item which is 'cgen.Assign("testing, "justForTesting()"))`.

**Comment by navjotk** [comment]
They shouldn't hold the same. I would expect `self._pre_kernel_steps` and `self._post_kernel_steps` to be empty lists (`[]`) and not the same as `stmts`. 

Of course, having these two empty arrays is useless as well.

In fact I even remember deleting this bit of code and then it coming back a few PRs later because the later PR wasn't fully updated or something. So all in all, a good catch. Thanks!

Submitting another PR to fix this shortly.

**Comment by mlange05** [comment]
PR #123 addressed this, I believe, so closing.
