### ISSUE TITLE
Iteration extension

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#169]
This is not really an issue but more of a devellopement direction. We currently have a separation between `Iteration` objects and `symbolic` objects. More specifically, no symbolic operation can be done on Iteration objects. However in a more general case, we may want to have Iteration accepting any kind of Symbolic data (e.g including derivatives) in order to avoid "by hand" implementation of some aaource terms or receiver terms.

Currently when we do  `src.add(m,u)` it does not support doing ` - src.ad(m,u)` (adding the source with a minus sign) and extending it to something that would allow to do `(src.dt).add(m,u)` would allow to work with a lot of more general inversion objective function implementations

**Comment by mlange05** [comment]
OK, I'm not entirely sure how to do this neatly, but I feel you might be approaching this from the wrong end:
a) Making an `Iteration` object propagate any outer terms to it's multiple inner expressions is possible but tricky to generalise, since you are effectively implementing arithmetic on vector variables. At least I think this might get tricky, since you need to do some sanity checking to make sure that the propagated expression makes sense.
b) The real problem, I think, is that `src.add()` has the wrong argument structure. I think it should take an expression as input instead of symbols, so that you can easily negate the expression. For this I believe we need to separate the generic point-interpolation coefficients from the source expression that we are interpolating onto the grid points.

To do this I think we want the `PointSource` base to provide the `.add(target, expr)` function, which creates the list of `Iteration` objects and applies the interpolation coefficients to `expr` in the body expression. So then you can either write `expr` out explicitly in the application/example like this:
```
src = PointData(...)
src.add(target=u, src * dt *dt / m)
# to negate:
src.add(target=u, - (src * dt *dt / m))
```

or alternatively let the `SourceLike` class provide the `expr` as a property:
```
src = SourceLike(...)
src.add(target=u, src.expression)
# to negate:
src.add(target=u, - src.expression)
```

In the latter, the source object will have control over the expression and the target, allowing you to implement different types of source terms, I think. Does this sound like it would allow you to do what you want?

**Comment by mloubout** [comment]
I think your way of thinking is the right way to go. My only "concern" was the limited possibilities we currently have to handle source/receiver term which are `add` or `read` with fixed coefficients and expression. Generalizing the `SourceLike` object to handle expression instead of hard coding it inside would indeed broaden the possibilities and would allow to keep `Iteration` object to handle the expression itself. 

I will lok into it and see what we can do, but this is not on top of my list yet.

**Comment by mlange05** [comment]
I believe issue #189 is what you are after here, right? If so I think this can be closed.

**Comment by mlange05** [comment]
@mloubout Prod. Is issue #189 what you are after for this? If so please close this issue to avoid duplication.
