### ISSUE TITLE
Caching of generated code

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#186]
On our current FWI runs, most of the time is spent by the workers compiling code, running the DSE transformations etc. This is obviously needless repetition that we should be avoiding by caching these results. Although I call it caching of generated code in the issue title, I mean to suggest caching at a higher level than just the code since even the DSE need not be called. Feel free to suggest a different title for the issue.

**Comment by mlange05** [comment]
Devito-3.0 (a.k.a. `StencilKernel`) already caches based on a detailed representation of the generated IR tree (see PR #180) . Simply switching the First Touch loops to this should help a lot. For anything higher level than that generating rigorous cache keys becomes tricky, since you need to fix the exact input plus the exact option combination.

**Comment by mlange05** [comment]
OK amendment to the above: 3.0 `StencilKernel` generates the cache key according to the final IR state. We currently still force-generate and compile every time, but it's easy to switch once we're satisfied the cache keys behave as we'd expect.

**Comment by mlange05** [comment]
Picking up this issue again, I think we need to un-muddle what we mean by _caching_ here:
* `StencilKernel` operators actually do cache generated code on an object basis. This means that once an operator is created it can be re-used through multiple `.apply()` calls without incurring any DSE/DLE/codegen/compilation overheads.
* The current seismic examples negate this fact by creating new operators for each invocation, thus forcing a complete DSE/DLE every time.
* Creating a generic caching mechanism that reliably pre-empts DSE (the first stage of creating an operator) requires us to encapsulate some measure of the input state and all potential transformations, given a particular parameter combination. *This seems incredibly hard to do well!*

Given that, I would argue that we should re-write the wrappers in `fwi_operators.py`/`tti_operators.py` to, at the very least, utilise a pre-setup operator across different invocations. In an ideal world, the 3.0 API should be powerful enough to completely remove these wrappers.

With that in mind I think this issue should be renamed to something like "Operator-caching in seismic examples".

**Comment by mlange05** [comment]
@navjotk It might also be useful to have a pseudo-code outline of the type of FWI/RTM loop you had in mind, so that we can discuss when and where different symbolic objects and operators need to be created to avoid re-compilation/re-allocation.

**Comment by navjotk** [comment]
The kind of caching you talk about already existed. The code was generated at operator creation time and multiple apply calls would call the same code. AFAIK this behaviour has remained the same since 2.0. 

This issue was about doing the kind of caching that you call *incredibly hard*.

Sympy caches its symbolic operations and potentially so can we, so that calling the DSE/DLE multiple times on the same input doesn't take the same time every time. 

If you want an issue about cleaning up for examples, please open a new one. That is not what this issue talks about.

**Comment by mlange05** [comment]
Ok, fair enough, let's call it something like "pre-emptive operator caching" or even better "form-caching", since this level of caching really requires a form compiler to capture symbolic equivalences as well (if you want to be thorough).

However, I really don't think implementing this is necessary at this stage due to the rationale outlined above. Previous experience from other projects also suggests that this type of form-caching can be a very harsh source of bugs, since any API change or feature that might affect the generated code in the slightest needs to be pre-emptively recorded in some type of parameter dictionary and used to form the hash key. Otherwise developers can easily get unwanted cache effects, where code changes seem to have no impact on the generated code, and user-side updates have no impact until the disk-cache is cleaned manually.

In any case, if you want to keep this alive, cool. Please change the title to something that does not alias with existing operator-caching. I'll create a new issue for the example re-structuring.

**Comment by navjotk** [comment]
Since code generation only happens at Operator instantiation (we all know that), caching of code generation clearly talks about a cache that operates between multiple Operator instances. IMO the original title was quite clear. I don't see what is "pre-emptive" about it. Nor do I follow the logical jump to a form compiler. I see the two as completely orthogonal. How is caching related to having a form compiler?

This cache is simply based on the definition of a function. Given the same set of input parameters, a function should produce the same result every time. If I already have the result for a certain set of input parameters, I shouldn't have to recompute it.

**Comment by mlange05** [comment]
My comments are intended to point out that a proper operator-level caching system will capture symbolic equivalence of the input (eg. `Eq(a + b)` and `Eq(b + a)`), which will require a more complicated analysis for certain types of equivalences. This is very close to a form compiler that translates any input equation to some cache-able unique intermediate representation. If you're willing to punt on symbolic equivalence, I see very little reason to implement under-the-hood caching only to fix the user-level design flaw of throwing away a perfectly good operator object, which we all know requires some heavy lifting to set up (as you correctly pointed out).

Also, just to clarify, we're talking disc-based caching, so as to capture multiple invocations of the same operator from different scripts/workers/runs, yes?

**Comment by navjotk** [comment]
The particular example that you use (`Eq(a + b)` vs `Eq(b + a)`) is captured by sympy as can be seen here:
```
In [8]: from sympy import Eq

In [9]: from sympy.abc import a, b

In [10]: e0=Eq(a+b)

In [11]: e1=Eq(b+a)

In [12]: e0==e1
Out[12]: True
```
It is possible that this doesn't work for more complicated equivalances (please do give some examples).

Since we're not losing symbolic equivalence, it makes sense to cache heavy operations like the creation of an Operator. That's the purpose of the cache in Sympy or anywhere. We aren't using the cache for its real purpose so far.

The way I see it the current design works well under certain assumptions. One of them being - "thou shalt always reuse Operator objects". This helps us remove that assumption. 
Less assumptions = simpler design. 
Simple is better than complicated.

**Comment by mlange05** [comment]
OK, out of interest, do you consider `Eq(a + b)` and `Eq(a.indexed[a.indices] + b.indexed[b.indices])` equivalent?

Aside from that, I still think that:
a) We need a reasonably comprehensive way of dealing with all the non-symbolic inputs into that define the operator-generated code (DSE/DLE/compiler settings, other types of flags - now and future). So I'd guess that solving issue #26 is a prerequisite for this level of caching?
b)IMHO, operator re-use is a good thing, since the implicit data-copies created through the current wrappers also create a non-negligible overhead. In other words caching the operators in the wrappers alone won't solve issue #227, since ultimately the data flow is wrong (see checkpointing example). So until we have a good automation of data flow scheduling that avoids unnecessary copy operations, it's a good thing we make users/app developers explicitly think about that.
c) Overall, I'm not completely against proper operator/form caching, but I see little gain and a large amount of potential of pain. So ultimately, if anybody wants to spend time on this, feel free, but I regard this as quite low-priority.

**Comment by mlange05** [comment]
Another interesting case for this discussion (I think) is whether we should/want to cache things like this:
```
In[]: from sympy import Function, Eq
In []: a = Function('a')(x, y)
In []: b = Function('b')(x, y)
In []: c = Function('c')(x, y)
In []: d = Function('d')(x, y)

In []: Eq(a, a + b) == Eq(a, b + a)
Out[]: True

In []: Eq(a, a + b) == Eq(c, c + d)
Out[]: False
```
Assuming that `a` is perfectly equivalent to `c` in all but name and likewise `b` is equivalent to `d`, should we cache the last expression/kernel? And if no (like sympy suggests), how does this relate to #225 and #230?

**Comment by mloubout** [comment]
I think this is fixed. Closing?

**Comment by navjotk** [comment]
I am not sure this is fixed. Code generation still always happens from scratch for every new `Operator` instance, right? We aren't even caching intermediate DSE/DLE results. Or are we (and I missed the PR that did this) ?
