### ISSUE TITLE
Merge compiler dictionaries

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#192]
There are two compiler dictionaries: one in `compiler.py` one in the DLE. The former should only contain compilation flags (but it has more, ATM), the latter should be a collection of compiler-specific pragmas. We probably need a single, centralised structure that includes and provide access to both dicts

**Comment by FabioLuporini** [comment]
There's no dictionary in ``compiler.py`` any more, AFAICT, @navjotk . We have ``configurations`` (our global state), and other stuff in ``dle/backends/utils.py``, which are just required by the DLE. Can I close this "issue"?

**Comment by navjotk** [comment]
I am not a fan of the current structure but sure, go ahead. Close this issue.

**Comment by FabioLuporini** [comment]
I'm all ears if you know a better way of structuring this 
In fact, I find it quite clean ...

**Comment by navjotk** [comment]
By having compiler specific elements in `devito/dle/utils.py`, you are making assumptions about the set of backends you ever want to support and by "hard-coding" them deep inside devito, the assumptions will probably spill out to the dle and probably beyond.

At some point, an abstraction called a Backend was proposed and started by @mlange05 that aimed to encapsulate all details of a backend. The idea was that when devito moves to a new platform, all required changes are encapsulated inside a backend. 

The whole point of this issue was to move these compiler specific details into some backend so that when you build a CUDA backend, we have a clean interface where just adding a new "Backend" class should be able to achieve what we want. 

This way we are also inviting contribution from the community since, if the backend specific details are in one place, someone going through our code needs to spend 30 minutes and can already contribute a backend class for their favourite backend.

Having these things hidden inside the DLE, as in the current structure, prevents all that.

So, in my opinion, we have moved in the opposite direction of "cleaner" since this issue was opened. However, you seem intent on doing this a certain way and I am not inclined to argue beyond a certain point.

**Comment by FabioLuporini** [comment]
if someone will ever want to contribute to our codebase  (hopefully !) I think finding stuff underneath ``dle`` will be the least of the problems. They are inside the ``dle`` because it's where they're used; just there, by the DLE

I agree, however, that we're missing this backend concept ATM. I also think it's a long shot from where we are now. IOW, I think that : 

> someone going through our code needs to spend 30 minutes and can already contribute a backend class for their favourite backend.

They'll need **much** more than that

I'll leave the issue open for now

**Comment by FabioLuporini** [comment]
The DLE is specializable by a backend (YASK does that), and so is the "compiler dictionary" (which, in fact, is more of a bag of keywords to generate OpenMP/SIMD code, at this point)

closing
