### ISSUE TITLE
StencilKernel with save

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#197]
I am not sure if it is an issue or just an in progress I am not aware of but it looks like that setting `save=True` is completly ignored by StencilKernel that always runs with cyclic indices.

**Comment by mlange05** [comment]
Yes, the old `save` flag should is currently ignored by the new API. Instead the cyclic indices are driven by using a `BufferedDimension` instead of a `Dimension` index. For convenience we provide `t` to mean cyclic (buffered) time indices and `time` for the "unrolled" true time index. So for an unrolled `TimeData` object you would simply instantiate your symbol as `u = TimeData(dimensions=[time, x, y], ...)`. We can probably re-instate the old short-cut for convenience though.

**Comment by mloubout** [comment]
I find this `t` versus `time` convention quite confusing to be honest.

**Comment by FabioLuporini** [comment]
> We can probably re-instate the old short-cut for convenience though.

If we do, probably the flag only needs to be provided to the ``TimeData``?

**Comment by mloubout** [comment]
I agrre with @FabioLuporini, it was only previously needed because of how o`operaor` was working but should be fine only in `TimeData` now.
