### ISSUE TITLE
Source/receiver serial

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#198]
I think we should add openmp pargamas for the source/receiver part. In our examples it seems like a waste of time, however in practice, the loop over receiver/source can be quite big (tens of thousand of receivers) and would benefit from parallelization.

**Comment by FabioLuporini** [comment]
not that easy ATM because of the indirections when writing to ``u`` and ``v``. So, we know that this *is* safe (because there are no repetitions -- ie, a source is updated only once per time iteration), but I have to find a way to tell the DLE (which is responsible for the OMPization) about this property

**Comment by mloubout** [comment]
@FabioLuporini 
this is fixed right?

**Comment by FabioLuporini** [comment]
receivers are parallel
sources, in many cases -- when we cannot determine correctness -- are not. W/o the additional correctness checks, in some cases the source loop got parallelised but the results were incorrect...

**Comment by mlange05** [comment]
That sounds perfect, since `#sources << #receivers`. Should be good to close then. @mloubout ?

**Comment by mloubout** [comment]
Yep sounds good, closing
