### ISSUE TITLE
Performance count

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#208]
It seems like the profiler outputs weird numbers : 
```
nt = 4903
Section loop_p_src_0<3,1> with OI=0.72 computed in 0.003 s [Perf: 0.00 GFlops/s]
Section loop_p_rec_0<3,5733> with OI=2.91 computed in 3.812 s [Perf: 0.00 GFlops/s]
Section main<3,2802,1983,413> with OI=4.20 computed in 6246.826 s [Perf: 0.08 GFlops/s]
```
Even at 1 flop per point that's 2802x1983x413x 4903/(6246.826x1e9) = 1.8GFlop/s
And for the exact same model but less time-steps:

```
nt = 50
Section loop_p_src_0<3,1> with OI=0.72 computed in 0.000 s [Perf: 0.01 GFlops/s]
Section loop_p_rec_0<3,5733> with OI=2.91 computed in 0.022 s [Perf: 0.07 GFlops/s]
Section main<3,2802,1983,413> with OI=4.20 computed in 63.921 s [Perf: 7.43 GFlops/s]
````

**Comment by FabioLuporini** [comment]
I just quickly checked. `nt` seems to be the duration in ms, rather than the actual number of timesteps. So the 0.08 -> 1.8 GFlops/s might be explained.

Why there's such a big variation in performance between the two test cases is not clear. It could be that we're leaking memory, and in the first case we end up swapping to disk. This is not that unlikely, given that huge mesh size... now why we'd be swapping, that I still don't know. We should first check this out.

Things to try:
- Instruct us on how to reproduce
- Please, re-run the first model and after a few thousands of secs take a look at the memory consumption, from another shell on the same node. You can ``htop`` or even ``watch numastat -m``. Then share the output of these two commands somewhere

**Comment by FabioLuporini** [comment]
It is possible that we are swapping even in the second scenario with 7.43 GFlops/s, but the effect is less evident given the shorter duration.

**Comment by mloubout** [comment]
This i modelling only, I have 128G of RAM so no memory issue. ANd `nt` is the actuall number of time steps. As I  don't save the wavefield, the emory usage in both case is the same, the only difference is the printed performance that don't make sense.

All wath run with no legacy and advanced dse and dle

**Comment by FabioLuporini** [comment]
So the Perf problem is related to the fact that you see that ``3`` instead of ``nt`` in ``Section main<3,2802,1983,413>``. I re-checked my acoustic and tti problems and they are fine. So something odd is going on here, I need a reproducible test case.

BTW, out of curiosity, what's the memory consumption?

**Comment by mloubout** [comment]
No, the problem is `[Perf: 0.08 GFlops/s]`

**Comment by FabioLuporini** [comment]
> No, the problem is [Perf: 0.08 GFlops/s]

That's related to that ``3``

**Comment by mloubout** [comment]
Oooooh, that make sense :)

**Comment by mloubout** [comment]
@FabioLuporini Ignore all of that, I am a dummy who forgot to update master. Closing.
