### ISSUE TITLE
Rename TensorFunction

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#221]
The name for this class is not very informative nor intuitive about what the class does. Maybe a name like `TensorSymbol` is better.

**Comment by mlange05** [comment]
I've been contemplating a similar issue for a while now, and I'm actually tempted to argue the opposite direction here. Since the introduction of `Dimension` objects we now have two distinct types of "symbol": functions and indices - and our original naming convention does not make this difference very clear. I'd go as far as argue that, since we ultimately want to be a mathematical DSL, using the term "function" to denote symbols that we can take derivatives of seems much more intuitive. This would mean that `TensorFunction` is actually quite a good name, while terms such as `DenseData` and `TimeData` might need a re-think.

**Comment by navjotk** [comment]
The term `TensorFunction` still implies it is a function that operates on a tensor. That is not what it is. The name is still incorrect.

**Comment by mlange05** [comment]
Ok, having thought about this some more, I believe the "function working on a tensor" is not the right way to classify this, and neither is "TensorFunction" the correct term for what the class notates: a temporary array. 

In fact, looking at other PDE languages, I believe the convention used (and please correct me if I'm wrong), is to have a "Function" denote a "mapping of a value to a point in a grid" - ie. the symbolic object that (discretized) represents a multi-dimensional array. Along the same line of reasoning, a VectorFunction maps a vector of value to each point in the physical domain (eg. coordinates or a velocity vector), while a TensorFunction maps a tensor value (3x3 in 3D)  to each point. This also aligns well with the idea of a "Function" denoting a symbol I can take a derivative of.

In light of this, I'm bound to agree that "TensorSymbol" (or "TensorValue") is probably slightly more appropriate than "TensorFunction" for the current temporary array symbol. Similarly I would argue thought that "DenseData" should really be "ScalarFunction" (not "Function" to avoid SymPy aliasing for now), while we might build Vector/TensorFunction classes later to replace or specialise CoupoundData.

However, I think our current nomenclature is ultimately quite bad, and we should revamp it. I propose to create a clean API where we only provide `ScalarFunction`, `TimeFunction` and `SparsePoint`, as well as `Grid`/`Staggered` classes, while having data and/or shape attached to symbols is optional (although by default provided through the grid). This also entails that we don't need a separate class for temporaries that do not carry data in the user space.

Thoughts? @navjotk @mloubout @FabioLuporini @ggorman 

@navjotk I can file a new issue for this if you feel a a complete re-naming is beyond this issue.

**Comment by mloubout** [comment]
I agree that `DenseData` is not a very good name, however I find `ScalarFunction` quite odd. It hides its space dependency as scalar would mean constant (to me).
I'll do some digging to see if there is some better way to name it (when I find time).

I am also not a big fan of `Tensor` names personally and would raser avoid it (can be misinterpreted from some fields).

**Comment by mlange05** [comment]
Well I think the rigorous term is "scalar-value function", as opposed to "vector-valued function" or "tensor-valued function". I believe that distinction will become very important for staggered grids. The problem I have with the current names is that we should not conflate data/CS terminology in what ultimately should be a math language. Since we are not the first ones to tackle this problem though, I would look to other PDE DSLs - and here this nomenclature is common. More digging required though to be sure...

One idea here would be to alias also alias "Function" -> "ScalarFunction", so that our `devit.Function` becomes, at least in the symbolic part, a near drop-in replacement for `sympy.Function`, but our constructor API is quite different, so actual overloading won't work.

**Comment by mlange05** [comment]
@mloubout Also, I think the space-depency is implied by the term "Function" in all cases, at least in a PDE-solving context.

**Comment by FabioLuporini** [comment]
I agree current names are bad. I also think we should simplify everything. How about this:
- ``Function`` (yes, we'll have to alias SymPy's Function, ...) to replace both ``DenseData`` and ``TimeData``. ``Function``'s ``new`` method can then return an actual Function or a time-dependending Function, if this distinction needs to be maintained through two different objects (probably simpler)
- ``PartialFunction`` would be the equivalent of ``SparsePoint``
- ``Constant`` to replace the current ``ScalarFunction``
- ``Tensor`` to replace the current ``TensorFunction``

**Comment by mlange05** [comment]
I generally agree, and I have no problem starting to alias `sympy.Function`, if it is well documented - I'll see if I can make the constructor more compatible once we implement this change. Exceptions:

* Unsure about `PartialFunction`, although I can probably be persuaded
* `Scalar` seems sensible to me, but tensor seems very ambiguous in that case. Are these supposed to be for (DSE) temporaries only, or are we planning to use them in the user API at some point too? If the former, I'd be inclined to say `TemporaryScalar`/`TemporaryFunction`; if the latter how about `Constant` and `SymbolicFunction` (probably need to rename something else)?

**Comment by FabioLuporini** [comment]
> Unsure about PartialFunction, although I can probably be persuaded

A mathematician should shed some light on this

> Scalar seems sensible to me, but tensor seems very ambiguous in that case. Are these supposed to be for (DSE) temporaries only, or are we planning to use them in the user API at some point too? If the former, I'd be inclined to say TemporaryScalar/TemporaryFunction; if the latter how about Constant and SymbolicFunction (probably need to rename something else)?

The way I see it, only in the DSE, but who knows... the reason I chose ``Scalar`` and ``Tensor`` was precisely that: to be usable by users too.

I agree about ``Constant``; how about ``Constant`` and ``Array``? "array" is a lower level name, like a "temporary". I don't like very much "Temporary"
