### ISSUE TITLE
Multi-model

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#230]
This issue highlights the problem we currently have working with multiple `Model` instances.

A good example is as follow. In the case you know what the true velocity model is, you would want to compare the data generated with the true model with the data generated by your initial or inverted model to look at the similarity in the data and how well.badly it fits. The code would look like

```
m1 = Model(true_vp, ...)
m2 = Model(smooth)_vp,...)

wave_true = Acoutic(m1,...)
wave_smooth = Acoutic(m2,...)

rec_true = wave_true.Forward()
rec_smooth = wave_Smooth.Forward()

# Check differences
initial_objective = .5*np.norm(rec_true - rec_smooth)
#Plot it or whatever QC
```
The current issue is that `wave_smooth` uses the velocity model from `m1` leading ti `initia_objective=0` as `rec_smooth=rec_true`, while it shoulde be quite different.

**Comment by mlange05** [comment]
OK, I think this issue needs to be unpicked at various levels:

a) Should `m1.m` and `m2.m` have different symbolic names or should they both be called `m` in the discretised equation object? If it is the former, the simplest fix seems to be to allow the name to be set through the `Model` constructor.

b) This example relies on the automatic derivation of data during operator invocation, which most likely will fail to detect aliased symbols (ie. two instances of symbolic data `m` that are different but have the same name ). Whether this is even a bug or not raises the rather fundamental question posed in issue #225 of whether Devito should mimick SymPy here and cache those two instances as one, or allow explicitly created aliases.

c) What is the rationale for binding a specific model to an operator at initialisation time, rather than invocation time? The fixes in PR #223, and indeed the entire ethos of the 3.0 API re-write, are based around being able to re-use a single operator for multiple invocations with varying data. This leads to the general discussion in #227 of should we maybe instead aim to do something like this:
```
m1 = Model(...)
m2 = Model(...)
forward = acoustic.Forward(...)
rec_true = forward(m=m1)
rec_smooth = forward(m=m2)
```

**Comment by mloubout** [comment]
Concerning c), I understand the design, but it make the 'Model' object obsolete, and this class/module will eventually contain a lot more (interpolation on new grid, model constraints) that will be very tricky to handle if we remove it. The main idea (in my understanding) is to have a 'Model' that encapsulates the physical properties and should allow to have interleaving ones.

**Comment by mlange05** [comment]
I'm not sure I understand your comment on #230? Can you elaborate please why that would make the `Model` class obsolete?

**Comment by mloubout** [comment]
As I understand it `rec_true = forward(m=m1)` requires `m1` to be either an numpy array or a Symbolic object (`DenseData`,...). However `m1` is a `Model` object that does contains multiple arrays for the TTI case, and the two different models may only differ in one of the parameter (one with and one without `phi` for example). So passing the object a san input would require a rewrite of `StencilKernel` that may make it obscure or loose its generality.

So I do think fixing the symbolic behavior would be better, but I may be wrong.

**Comment by mlange05** [comment]
Ok, I think we need to separate multiple overlapping issues again:
* If operator-level symbol-caching is broken, we should fix it, regardless of this discussion. As pointed out above though, it looks to me like this is closely related to issue #225, and we might need to make a decision here first.
* Regardless of this bug, I believe the a premise of the example might be wrong. So, ignoring all implementation-related issues, what is the _algorithmic rationale_ for marrying a particular piece of data to an operator at initialisation? Is there a good reason, in theory, for not using the invocation-time overrides to re-use instantiated operators, or is all this discussion driven by previous design choices that might or might not be valid anymore? If so, let's please re-examine these.
* The implementation issue of: _"Given we have a class that acts as a collection of symbol-fields, how do we use the invocation-time overrides to facilitate operator re-use?"_ This one, I believe, comes with a bit of choices and questions:
  * Explicitly user driven: `forward(m=m1.m, phi=m1.phi)` and `forward(m=m1.m, phi=m2.phi)`. If the set of fields per model is big, this will lead to a somewhat cluttered and unfriendly interface.
  * Implicit, with distinct collections (`Model` objects): `foward(model=m1)` and `forward(model=m2)`, where the `apply()`/`__call__()` methods on the operator have been overriden to unpick a given model instance. This may look cleaner, but might lead to unnecessary data replication, if for example `m1` and `m2` share certain fields but not others. Then again, this can probably be solved by `Model` objects inheriting/being created from others - a set of use cases would be helpful here, I think.
  * Possibly some combination of the above: `forward(model=m1)` and `foward(model=m1, phi=m2.phi)`. Potentially powerful, but also potentially very confusing...
* Another design issue is, whether `Model` should even be a "bag-of-fields"? If not, it might inherit from `DenseData` to make it directly compatible and provide utility function, like creating from `vp`. I believe this route will probably require the introduction of some type of "Grid" class to provide things that define data layout, like `shape_domain` (grid shape including PML layers), so that other "utility fields" (eg. `phi`) can all be created from one `grid` object.

**Comment by mloubout** [comment]
>Implicit, with distinct collections (Model objects): foward(model=m1)
I think it would be dangerous to have ` StencilKernel` even know about `Model`. Marrying devito to our examples would limit its application.

>what is the algorithmic rationale for marrying a particular piece of data to an operator at initialisation?

The main idea was to have a `Model` and a `Data` object that contains all the metadata necessary to create the solver as well as the data values and/or paths to disk locations. This alows to have an inversion workflow fully driven by your recorded data. This goes back to the `inversion` repo where all src/rec positions are from file at runtime, same for model size, values, ....

**Comment by mlange05** [comment]
> > Implicit, with distinct collections (Model objects): foward(model=m1)

> I think it would be dangerous to have StencilKernel even know about Model. Marrying devito to our examples would limit its application.

This wouldn't happen in the main `StencilKernel`/`Operator`, but instead we would sub-class an operator to add additional overrides to the `apply()` method. This way the specializatiion would still be specific to the examples. As in:
```
class ForwardOperator(Operator):
    def __init__(model, src, rec, ...):
        eqn = some_stuff_using(u, nodel.m, model.phi, ...)
        super(ForwardOperator, self).__init__(stencils=[eqn, src_term, rec_term], ...)

    def apply(model, src, rec, u, ...):
        super(ForwardOperator, self).apply(u=u, m=model.m, phi=model.phi, ...)

**Comment by mloubout** [comment]
Fixed, closing
