### ISSUE TITLE
ABC

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#231]
This is not really an issue, but a discussion on how to setup Absorbing Boundary Conditions properly ditching the (useless) damp field. The good thing is that we have analytical expression as a function of the index so we can write it symbolically. The bad news is it kinda look messy the way I see it.

Fot a 1D problem (simpler to write here) it would look like:

```
abx_0 = 1-exp(-(0.004*(40-i+1))^2) # expression as a function of the distance to the border 
abcx_n = 1-exp(-(0.004*(40-i+1))^2) # expression as a function of the distance to the border 
```
the at the `StencilKernel` declaration

```
stencils = [eqn] + rec + src + abcx_0 + abcx_n
```

What I don't know how to handle is, this is not a Data object, only a symbolic one, so I guess `i` should be a  `Dimension` object. I just don;t see how `Dimensions` handle their own origin. Maybe the new `pointdata` @mlange05 made could help this.

NOTE: I will keep editing  this issue with more details/ finding but any input is welcome.

**Comment by mlange05** [comment]
Ok, so I think the real problem with this is that the expression itself uses explicit indices, whereas the current API assumes that expressions work over all points in a grid irrespective of the grid index. This is similar to the numpy vectorisation API, which allows/requires you to remove all explicit loops, thus hiding the loop index that the ABC expression depends on. The usual trick in numpy around this is to use `np.meshgrid` or `np.mgrid`, but I wonder whether we can't come up with a better way to avoid the memory burden of explicitly storing grid coordinates in a field?

On a higher level, I also think that this problem really requires us to get concrete on the implementation of a `Grid` abstraction, since nothing in the current core code deals with the concept of an "origin". Whether and how this relates to point-data interpolation, I can't really comment on at this point, but my intuition is that grid spacing (`h`), which we simply assume in various places, will probably need to be defined in some way by such a grid abstraction.

**Comment by mloubout** [comment]
#305 should do it.

**Comment by FabioLuporini** [comment]
what's the plan here @mloubout ?

**Comment by mloubout** [comment]
@tjb900 has an nice example, I have a branch with it too but I need a bit of time to clean it up.

**Comment by FabioLuporini** [comment]
define "bit of time" ? :D

I think we now naturally support this via subdomains . Perhaps we should write a simple notebook.

**Comment by mloubout** [comment]
Runs decently with subdimensions but was a few months ago. Hadn't had time to look back at it
