### ISSUE TITLE
Test for BufferedDimension does not actually test it

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#235]
The test [here](https://github.com/opesci/devito/blob/master/tests/test_stencil_arithmetic.py#L117) is supposed to test `BufferedDimension`, going by the name and the docstring of the test. However, I see no code here that suggests that a `BufferedDimension` is actually being tested.

**Comment by mlange05** [comment]
Note: the updated test location is [here](https://github.com/opesci/devito/blob/master/tests/test_operator.py#L116).

Ok, so the use of the word "buffered" in the docstring has actually nothing to do with the `BufferedDimension` class, but instead refers to the fact that this test does a complete "buffer copy" by having separate leading dimension indices on LHS and RHS of the assignment. Thus, rather than doing an in-place operation it copies the complete content of a buffer to the next one, eg. `a[1, :, :] = a[0, :, :]`. This is in contrast to the test above it that does in-place stencil operations.

Also, more tests of actual timestepping loops that use `BufferedDimension` objects can be found [here](https://github.com/opesci/devito/blob/master/tests/test_timestepping.py).

@navjotk Is this explanation sufficient to close the issue, or would you like me to update the docstring? If so, what was unclear in particular (I don't think it mentions the `BufferedDimension` class)?

**Comment by navjotk** [comment]
I think what confused me was _"with buffering dimension in indexed expression format"_. Would it be possible to reword this so as to not use the words _buffering dimension_ together? :)

**Comment by FabioLuporini** [comment]
can we close this? I think it's nitpicking, or pls update the docstring and close the issue

**Comment by FabioLuporini** [comment]
Can we close this?
