### ISSUE TITLE
Back to time bounds

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#251]
This is a bug I came accross helping emma.

The time loop bounds are always derived from the presence of a source or some receivers. The issue is that for a trivial stencil such as :

```
u = TimeData(name='u', shape=(100, ), time_order=1, space_order=2, time_dim=100)
# Derive the stencil according to devito conventions
eqn = Eq(u.dt,  u.dx)
stencil = solve(eqn, u.forward)[0]
op = Operator([Eq(u.forward, stencil)], subs={h: dx, s: dt})

# Execute the generated Devito stencil operator
op.apply()
```

will only execute 2 time step (`Section main<2,99>`) unless `u` is declared with `save=True`. It turns out, `TimeData` object do not have any recollection of the dimension of the time axis once initialized as is is turned into the shape of `u` which is `(2,100)`.

**Comment by FabioLuporini** [comment]
Because the time dimension in ``shape`` is automatically recasted to 2 when ``save = False``. Look at the code here in ``interfaces.py``:

`
            if not self.save:
                time_dim = self.time_order + 1 
                self.indices[0].modulo = time_dim
            else:
                if time_dim is None:
                    error('Time dimension (time_dim) is required'
                          'to save intermediate data with save=True')
                    raise ValueError("Unknown time dimensions")
            self.shape = (time_dim,) + self.shape
`

And as far as I can tell from a simple ``git log -L510,518:interfaces.py``, you and @mlange05 touched that piece of code a few times. So I'm not sure what's the behaviour you would expect at this point

**Comment by mloubout** [comment]
Yes, mainly @mlange05 and I kinda broke that part, I am just not sure how to keep track of the time axis size properly.

**Comment by mlange05** [comment]
Ok, so the problem is that a `TimeData` object with buffered time dimension can not / should not know about the full extent of time (it's buffered, it can go on forever). This means that an explicit value for `time` needs to be provided at call-time rather than object creation. The explicit dimension overrides seem broken as well at the moment though, and I'm working on a branch to fix this. I've also added a warning in that branch that `time_dim` will be ignored if `save=False`, and we'll probably want a run-time error forcing users to provide a `time` or `t` value instead.

**Comment by FabioLuporini** [comment]
BTW, can we not drop ``time_dim`` and simply pass the information as first entry of the shape? In the end, this is a ``TimeData`` object...

**Comment by FabioLuporini** [comment]
Also, this might impact #236 ( @navjotk )

**Comment by mlange05** [comment]
Well no, since the sole use of `TimeData` at this point is to implicitly add the time dimension and shape. If you start passing the dimension shape explicitly, you might as well pass the time symbol (`t` or `time`) explicitly, otherwise the tuple dimensions don't align. And at that point you might as well drop `TimeData` altogether and just use `DenseData`...

> Also, this might impact #236 

It does, and I have a fix, which effectively follows the same rationale as above: make time dimensions implicit in `dimensions` argument, just as it is in `shape`. Will push soon...

**Comment by FabioLuporini** [comment]
> Well no, since the sole use of TimeData at this point is to implicitly add the time dimension and shape. If you start passing the dimension shape explicitly, you might as well pass the time symbol (t or time) explicitly, otherwise the tuple dimensions don't align. And at that point you might as well drop TimeData altogether and just use DenseData...

Well, ``TimeData`` does many other thigns AFAICT, so you'd still need it, I think. But anyway, this is another story, let's not get distracted...

**Comment by FabioLuporini** [comment]
I think this can be closed, @mlange05 ?

**Comment by mloubout** [comment]
I think this is done

**Comment by FabioLuporini** [comment]
Right, closed.
