### ISSUE TITLE
outdated examples

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#254]
``example_gradient`` and ``gradient_example`` need to be updated to 3.0

BTW, introduce name convention? (eg, drop "example" ?)

Note that some initial tweaks are already in #253

**Comment by navjotk** [comment]
`example_constant` (not `example_gradient`) and `gradient_example` were introduced by PRs #233 and #242 respectively and broken by #243.

I have been trying to fix `gradient_example` and have commented on #243 about the problem I am facing. 

I think @mloubout is the best person to work on fixing `example_constant` since I don't yet understand how that example is supposed to work.

**Comment by FabioLuporini** [comment]
OK, so I'm also appending @mloubout to the "Assignees" list

**Comment by mloubout** [comment]
On it, should I just commit it to the PR or make a different one.

**Comment by FabioLuporini** [comment]
if it's not a major rewrite, just add it; otherwise new PR would be better, but no worries it's OK in either way

**Comment by mloubout** [comment]
Most of it in #256

**Comment by mloubout** [comment]
Closing?

**Comment by FabioLuporini** [comment]
Yes, closed.
