### ISSUE TITLE
Time subsampling

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#267]
```
                if dim_sizes[dim.name] is None:
                    # We haven't determined the size of this dimension yet,
                    # try to infer it from the data shape.
                    dim_sizes[dim.name] = shape[i]
                else:
                    # We know the dimension size, check if data shape agrees
                    if not dim_sizes[dim.name] <= shape[i]:
                        error('Size of dimension %s was determined to be %d, '
                              'but data for symbol %s has shape %d.'
                              % (dim.name, dim_sizes[dim.name], fname, shape[i]))
                        raise InvalidArgument('Wrong data shape encountered')
```

So I guess this part is to avoid segfault, however, in case of time subsampling, the field saved has less time step than the time axis so this makes it impossible.

**Comment by mlange05** [comment]
Ok, so this issue is really not helpful in its current form. Since time sub-sampling is clearly not supported at this point, it would be much more productive to write out a detailed spec for the desired features, rather than speculating about which particular lines in the code may or may not need changing to implement it. For example, assuming we want to sub-sample at factor 4,

* We need buffered time in between sub-sample "dumps", right? Do we want copy into a separate field/buffer or do we need some clever buffer switching to move between t0, t1, 2 and the semi-unrolled buffers? To illustrate (`-` indicates throw-away buffers), are we doing:
```
-----------------
x   x   x   x   x
```
or are we doing
```
 --- --- --- ---
x   x   x   x   x
```
* If we want the latter, what might this look like in the code, in terms of conditionals and modulo arithmetic? Would/should the `-` and `x` data points even be stored in the same data object? 
* How would one express this in the high-level or "indexed" API? A new or adjusted type of `Dimension`, eg. `DerivedDimension` that encapsulates an expression of how it relates to its parent dimension?

**Comment by FabioLuporini** [comment]
@mloubout I only re-read it quickly; is this still an issue?

**Comment by mloubout** [comment]
I don't think so, argument/paraemeter engine is now way more stable and robust. Closing
