### ISSUE TITLE
Consolidate compiler settings for different platforms

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#28]
Compiler flags and other settings that change between different backends could be consolidated in a "backend" layer between the JitManager and the compiler. There could be various backends like:
- Serial (no parallelisation)
- OpenMP for Xeon on GCC
- OpenMP for Xeon on Intel compiler
- OpenMP for KNC
- OpenMP for KNL
Choosing between these backends would require an environment variable.

This was suggested by @mlange05 . Inviting discussion on this implementation here.

**Comment by ggorman** [comment]
It's not completely obvious. On the Xeon, KNC and KNL there is a good
argument for using Intel compiler directives. Of course this creates other
problems when he compute nodes don't have a compiler. However, we have at
least one system that has *no* compiler on the compute nodes. Pros and cons
need to be debated.

**Comment by mlange05** [comment]
Ok, to support the more exotic systems I would still advocate supporting overrides with standard names (CXX, CXXFLAGS, LDFLAGS, etc.) to give the user individual control if they wanted to. The core point of providing pre-defined backends is that we should provide users with a set default flags/settings for well known compiler/architecture combinations that we test and vouch for, ie. KNC with Intel. This is aimed at auto-managing the wealth of run-time options that we otherwise have to manage via env vars or config files. Currently, we rely on `codepy` to pick our flags from the Python build, and then adjust it according to some internal, undocumented logic, which is not a great thing to do.

**Comment by navjotk** [comment]
I am not convinced CXXFLAGS is the best way to go in this case. You are saying we would have an 'automatic mode' where the flags are automatically chosen based on @pvelesko 's work mostly. And a manual mode where the user specifies each flag he wants. There should be something in between these two where I don't want to have to choose every single flag- use your own sensible defaults - except for a single one - architecture for example. In other words, if devito has chosen a set of 15 compiler flags for a MIC architecture, for example, and I want to add a single flag of my own to the mix, should I have to rewrite the 15 existing flags into the CXXFLAGS variable to be able to add single one of my own?
This is where having separate ADD_FLAG and REMOVE_FLAG help.

**Comment by pvelesko** [comment]
Yes so what I'm planning on doing next is adding a single env var DEVITO_ARCH = knc/knl/x86 
based on this flag I will adjust several things such as add different compilation flags as well as choose a blocking mode (manual vs directive based) where sensible.  This will also allow us to have some constants such as cache sizes for making a good initial guess on the proper block size. Along with this commit I have in mind we'll also implement Intel auto-tuning tool which will give us flexibility and allow for self-tuning to the best block size. 
I think this is the most sensible thing to do because picking stuff like out automatically can be confusing because KNL supports both x86 and MIC-AVX512 instruction sets. Furthermore, this will allow for easy cross compilation?

**Comment by mlange05** [comment]
The recent PR #39 addressed large parts of this. Are we happy for this to be closed now, or do we want to wait until we have honed the compilation flag presets and have the benchmark numbers to back them up?

**Comment by navjotk** [comment]
I think this can be closed.
