### ISSUE TITLE
Reverse flag for time

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#281]
Just an issue a bout the reverse flag.

Currently, the time loop is written at the first invocation of `apply()` with the current `reverse` property of the global `time dimension`. This is problematic if anither operator with a different flag has been created in the mean as it would change the time axis.

**Comment by FabioLuporini** [comment]
This is gonna disappear automagically once Navjot's arguments handling magic is in. So assigned to him

**Comment by mlange05** [comment]
@FabioLuporini @navjotk Not necessarily, since we'll probably keep an explicit flag to indicate direction, as discussed in #247. The problem with this bug here is that the `Iteration` objects for time in both forward and backward operators read their direction from a global `time` dimension - and what's more they do this during `.ccode`, which is delayed until the first `operator.apply()`. So the first operator reads the dimension direction after the second one has changed it. The fix should be easy, and I'll try to come up with a test for the problem.

**Comment by navjotk** [comment]
#283 offers a fix for this but maintains the stateful `reverse` flag on the global object representing the time dimension. This can potentially cause issues if two `Operator` constructors are running in parallel - one with `reverse = True` and one with `reverse = False`. I argue that having state on a global object is so evil, it should be avoided at all costs. 

There have been various suggestions on how to avoid global state at the design level. I am compiling them along with the associated discussions here to enable further discussion:

### Suggestion 1:
>`_schedule_expressions` could pass the reverse flag to the Iteration constructor from the `Operator`'s `reverse` property, without ever having to store it on the `Dimension`.

@mlange05 's response: `schedule_expression` creates (multiple) `Iteration` objects per `Dimension`, so somehow bypassing the parent object (dimension) when injecting additional information into the derivative object (iteration) defies the point of deriving it from the dimension in the first place. At the very least this sounds counter-intuitive, and no better than the current state hackery, at least IMHO.

My response: Deriving information from the parent object does not require storing any information on the parent. The same could easily be achieved by having a dict mapping `Dimension` objects to their direction (among many other possibilities). I don't see how creating multiple `Iteration` objects per `Dimension` makes anything different.

### Suggestion 2:

> Have a time_r dimension internally, which the Operator switches to, transparently, when it receives a time_axis=Backward

@mlange05 's response: Trickier than it might seem, since it effectively comes down to applying a subs({time: time_r}) over all received expressions. But what about t, or even some other derived t_s (eg. for sub-sampling)? What about time in the src/rec terms? I think this approach is really only safe if the user has full control of choosing the symbols for each term, but that makes the API slightly messier due to various built-in variants of "time".

### Suggestion 3:

> Allow `Operator`s to accept dimensions at construction time (through `kwargs`), with the following syntax (definitely improvable):
> `Operator(..., t=REVERSE)`
> `REVERSE` is a special object (there can be many...) that is telling the `Operator` to traverse all iteration loops using dimension t in the reverse direction. The constructor propagates this information to schedule_expression, which will then know how to construct the t loops. This way, no internal state is changed. Also, the solution becomes completely general (we'd not be specialising time...)

@mlange05 's response: Hmmm ok, I don't really like this approach either, since it effectively encapsulates the functionality of generic "derived" dimensions but it forces us to encode each transformation in a special-case object, just like `REVERSE`. A more natural way would be to say `time_r = DerivedDimension(expr=time_end - time)` (or anything similar that permits generic expressions rather than hard-coding individual transformations) and then do `Operator(... subs={time: time_r})`. But at that point we are back to whether we should even use a derived dimension to encapsulate "reverse-time" or not and how to deal with granularity (see above discussion).


I would still argue for Suggestion 1 since it removes global state with no change in our API.

**Comment by FabioLuporini** [comment]
Excellent, thanks

**Comment by navjotk** [comment]
As explained in the slack channel, this issue might now be a blocker for checkpointing. 

Documenting another suggestion here (originally by @jhueckelheim ):
Every `Operator` make its own internal copy of the global dimension objects at construction time.

**Comment by mlange05** [comment]
> Every Operator make its own internal copy of the global dimension objects at construction time.

Technically not a solution, since it only decreases the critical region of code during which the potentially fatal interrupt in a multi-process settings could happen to "between entering the constructor and the dimension deep-copy".

>  I argue that having state on a global object is so evil, it should be avoided at all costs.

While true on a conceptual level, I in no way share your urgency, since I see this as an _extremely unlikely_ corner case. Personal opinion on both sides though, I would say, so up in the air...

> As explained in the slack channel, this issue might now be a blocker for checkpointing.

I have not fully understood your concerns here, so I will need to get back to you on this one.

On top of the comments above, I would argue that this issue is strongly linked to time-sub-sampling (issue #267) and other potentially related use cases where we _derive one iteration space (dimension) from another_. I would generally argue that whatever mechanism we come up with to solve this should also work for #267 and be generic, so that we can capture BCs on sub-regions or "expanding box" formulations as well. This of course is up for debate, so input welcome

**Comment by navjotk** [comment]
> Technically not a solution, since it only decreases the critical region of code during which the potentially fatal interrupt in a multi-process settings could happen to "between entering the constructor and the dimension deep-copy".

If you don't do anything to the global dimension before making the copy, the size of that region is 0.


I see no advantage to have `Dimension` objects globally shared between multiple `Operator`s. Only disadvantages.

**Comment by mlange05** [comment]
> If you don't do anything to the global dimension before making the copy, the size of that region is 0.

That's still enough for an interrupt. Unless you make the combined copy-and-global-change operation atomic or use some lock on the variable you still haven't actually solved the synchronity issue. Btw, would you consider variable locking as a potential solution? @navjotk 

> It is my personal opinion that global state leads to race conditions? Should I even bother to give references for this one?

> I see no advantage to have Dimension objects globally shared between multiple Operators. Only disadvantages.

Neither of these is under discussion here. In fact I do not like the global-state-change solution either (and was outvoted at the time), for one simple reason: the very existence of this issue demonstrates that on a conceptual level `time != reverse_time` (I am yet to hear a non-implementation related argument against this, btw). So, again, as stated before, I believe this is a self-inflicted problem, based on the fact that the conceptually clean solution (multiple objects/symbols; suggestion 2) becomes messy and inconvenient in practice due to having a large number of symbols. 

Now, if we want to avoid the multi-symbol option by somehow forcing two conceptual dimensions onto the same symbol, I prefer the global state solution (my personal opinion), since the very low and contained risk from potential synchronicity issues for me is the lesser evils over manually forcing one iteration object to be special (by whatever means) during operator construction. My rational is that the hackery (justifiable by the "time is special" argument) should be contained to the highest level of abstraction we provide instead of deeply penetrating the iteration AST. Moreover, I think it should also be contained to the direction of time only, ie. things like sub-sampling, modulo buffers, sub-regions, etc should still have a generic "derivation mechanism" based on symbolic expressions rather than hard-coded operations.

**Comment by navjotk** [comment]
> That's still enough for an interrupt. Unless you make the combined copy-and-global-change operation atomic or use some lock on the variable you still haven't actually solved the synchronity issue. Btw, would you consider variable locking as a potential solution?

You don't need to change the global object at all. You make a local copy first, and only modify the local copy. These are atomic operations since global state does not change no matter where the `Operator` constructor is interrupted. The synchronicity issue exists because different `Operator`s share the same `Dimension` objects. Removing that shared assumption, the issue being discussed here does not exist.

**Comment by mlange05** [comment]
I'm not sure I understand how you want to do this then - aren't `Dimension`s globally cached SymPy symbols? How do you suppose to deep-copy that and then inject that copy into any received set of expressions?

In any case, I have outlined my reasoning above. If you are happy that this solves the race conditions issue, please go ahead.

**Comment by mloubout** [comment]
Isn't his fix?
