### ISSUE TITLE
FixedDimension has to go

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#372]
Full discussion on slack

Code-generation API can not create interface object that don't make sense for cleanup purposes.

**Comment by mlange05** [comment]
Ok, first of all, polemic titles like this are not helping anyone. `FixedDimension` objects will most definitely stay, _if_ (and only if) the concept of fixed dimensions even survives at all.

Now for the technical explanation:
a) The introduction of a specialised `FixedDimension` type **is not merely "for cleanup purposes"!** The concept of fixed dimensions is naturally incompatible with certain aspects of more advanced features that we are working on, eg. checkpointing or MPI support. As such, having regular dimensions and fixed ones present as the same object type throughout the code generation engine is making developing these features extremely difficult. Hence separating the types makes a lot of sense, and paves the way for these new features.

b) The real problem with fixed dimensions is that the default dimension used by function symbols are currently managed globally, and thus runtime injection of specialised dimensions is tricky at best. This is the reason that the fixed-dimension test in `test_adjointA.py` was recently disabled. A more comprehensive solution to this problem is to not use global dimension symbols as defaults, but build them on a per-case basis. This can be done via the newly introduced `Grid` classes and I'm working on a new API to facilitate just that. 

c) **Important:** The concept of a "fixed dimension", ie. hard-coding loop bounds, is **a purely low-level compiler feature** and not part of any formal mathematical abstraction Devito provides. It is largely kept around for legacy purposes and was introduced as an implementation shortcut in Devito-2.0 (Propagator). As such, **no high-level domain-specific application should depend on this feature!** After all, Devito operators are supposed to be black boxes where the engine decides how best to solve the given mathematical definition in the fastest way, leaving low-level implementation details, such as loop bounds, to the compiler engine. **This is the essence of software abstraction!**

**Comment by mloubout** [comment]
>FixedDimension objects will most definitely stay, if (and only if) the concept of fixed dimensions even survives at all.

Since when?

>features that we are working on, eg. checkpointing or MPI support. As such, having regular dimensions and fixed ones present as the same object type throughout the code generation engine is making developing these features extremely difficult

After spending three weeks telling me that the features we are working on is not an argument for not having it, the argument is because your features need it?

>The concept of a "fixed dimension", ie. hard-coding loop bounds, is a purely low-level compiler feature and not part of any formal mathematical abstraction

I don't agree, wether the loop size is in the signature or the loop itself, the problem solved is exactly the same. `FixedDimension` decides it's not. The mathematical abstraction/problem does not care where the dimension size is known.

>Devito operators are supposed to be black boxes where the engine decides how best to solve the given mathematical definition in the fastest way, leaving low-level implementation details, such as loop bounds, to the compiler engine.

Except now, Devito doesn't decides anything, there is only "all loop size must be inputs" choice because you decided so.

**Comment by mlange05** [comment]
> > FixedDimension objects will most definitely stay, if (and only if) the concept of fixed dimensions even survives at all.

> Since when?

Fixed dimension are an obsolete feature ever since the generalization of loop bounds in Devito-3.0. They have no proven benefit and cause a large amount of unnecessary special-casing in the code generator. The only reason they still exist is because SLIM depends on them, and the API change was needed to amortize the codebase against existing and further special casing, so that we can move forward. Therefore the class `FixedDimension` needs to stay, while the API to enable their usage is still under development.

> After spending three weeks telling me that the features we are working on is not an argument for not having it, the argument is because your features need it?

Both arguments are true, none are relevant to the discussion; the codebase becomes cleaner and it makes further development easier.

> I don't agree, wether the loop size is in the signature or the loop itself, the problem solved is exactly the same. FixedDimension decides it's not. The mathematical abstraction/problem does not care where the dimension size is known.

Brilliant, we agree: the mathematical abstraction does not care about a known dimensions size. Hence, any high-level seismic abstractions should not either, as it does not change the behaviour of the operator that Devito generates from the given problem specification.

> > Devito operators are supposed to be black boxes where the engine decides how best to solve the given mathematical definition in the fastest way, leaving low-level implementation details, such as loop bounds, to the compiler engine.

> Except now, Devito doesn't decides anything, there is only "all loop size must be inputs" choice because you decided so.

Devito does make a decision and it is not to use fixed dimensions(!) - again, because they have no proven value except for legacy compatibility. The statement that "all loop size must be inputs" is also simply false(!), since Devito will figure them all out for you during the `operator.apply()` call.  This interface is **the official interface to use for Devito operators!** If you choose not to use these public and supported interfaces, and instead bypass the parameter automation step, it will create a massive amount of work on the application side as we develop Devito and implement further features, which ultimately constitutes a non-maintainable model of software development (more in the relevant slack channel).

**Comment by mloubout** [comment]
Agreed on and fixed in #373, closing
