### ISSUE TITLE
Accept grid as an argument to Operator.apply

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#409]
`Operator.apply` should accept arguments of type `Grid` to override spacing (`h_x`/`h_y` etc.) values. The grid size can also be used to double check array sizes and loop bounds etc.

**Comment by FabioLuporini** [comment]
I guess no need for this anymore, as we're currently extracting the Grid for each Function the Operator will run with, and checking that it is indeed unique. Thoughts @navjotk ?

**Comment by navjotk** [comment]
Can you elaborate on what you mean by "extracting the Grid for each Function the Operator will run with, and checking that it is indeed unique"?

**Comment by FabioLuporini** [comment]
``Grid``s are attached to ``Function``s, so there should be no need for explicitly passing a ``Grid`` to ``apply``. Within ``prepare_arguments``, we iterate over all functions to fetch their Grids; all Functions should be defined on the same Grid, otherwise an exception is raised. Such Grid can be used to override spacing and origin values.

**Comment by ggorman** [comment]
Abstractions have changed significantly since this was opened. No longer relevant.
