### ISSUE TITLE
Ambiguous API

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#437]
say I provide two Eqs:
```
A[i] = A[i] + j
B[i] = f(A[i])
```
where both `i` and `j` are `Dimension`s.
The code I'm gonna generate is:
```
for i
  for j
    A[i] = A[i] + j
  B[i] = B[i] + f(A[i])
```
What if instead the user wanted something "less natural" such as:
```
for i
  for j
    A[i] = A[i] + j
    B[i] = B[i] + f(A[i])
```
An analogous situation was encountered by one of the users (see Gary's bug in Slack's #questions):
```
for t
  for x
    for y
      for z
        A[x, y, z] = f(B[t, x, y, z])
for x
  for y
    A[x, y, 0] = A[x, y, 10]
```
Now `A` logically depends on `t` , but (with current ``master``) it's gonna be scheduled outside `t` although (logically) it should be inside

Thoughts?

**Comment by mloubout** [comment]
I have trouble understanding what this is supposed to do.

For the first two schedule, the result should be the same, second one only keeps overwriting `A` so unless something else is done with `A` at each time step, it doesn't really matter.

As for the last one, `A` does not depend on `t` it only depends on `f(B[t_last, x, y, z])` as again it only gets overwritten at each time step util the last, and scheduling ` A[x, y, 0] = A[x, y, 10]` after the time loop should give the correct answer.

**Comment by FabioLuporini** [comment]
> For the first two schedule, the result should be the same, second one only keeps overwriting A so unless something else is done with A at each time step, it doesn't really matter.

the second one is actually incrementing into ``A`` (adding j at every j step)

As for the last example, this is what Garyd's code does: https://github.com/gamdow/ACG-feasibility/blob/dev/DevitoRKInSingleStep.ipynb 
More info in Slack's #questions. If you try running it, you'll see what I'm referring to. Could you take a look?

**Comment by mloubout** [comment]
>the second one is actually incrementing into A (adding j at every j step)

So does the first one, last value of j always end up in B inside or outside the loop.

Will look into Garyd's code (gonna take a bit of time, quite heavy)

**Comment by FabioLuporini** [comment]
> So does the first one, last value of j always end up in B inside or outside the loop.

oh, fine, I updated it to make it an increment over B. Regardless of the final values, my concern was about the loop structure.

And about Garyd's code, yes, that was my impression too, but again regardless of what he's trying to do, the ambiguity is still there and (I think) should be solved. 

IOW, I think we might reformulate the problem as: "What can the user do to steer the loop nest construction (ie, to alter the default synthesis rules)?"

**Comment by mlange05** [comment]
Ok, a summary of what was discussed on Slack:
The key observation, IMHO, is that in both example cases a _reduction_ is followed by a tensor expression, where the reduction is implicit due to the fact that the RHS has one more dimension than the LHS (eg. we reduce over `j` and `t` respectively). Using this interpretation removes all ambiguity, as far as I can tell, as the second expression in both cases now depends on the _result of the reduction_, not it's individual components, as indicated by the fact that the "reduced" dimension (`j`/`t`) does not show up in the the second expression (`B[i] = f(A[i])` and `A[x, y, 0] = A[x, y, 10]`).

Following from this, I believe the first answer for example 1 is the "correct" interpretation and the code snippet for the second example is correct. Moreover, if the second expression in the time-based example is supposed to be part of the time loop, making `A` time-dependent (eg. `A[t, x, y, o]`) will cause the compiler to do just that.

**Comment by FabioLuporini** [comment]
Closing
